health_check_url_enabled: true
health_check_url:
  csipublisher:
    - http
    - 8080
    - swagger-ui.html

chk_tomcat_services: false

health_check_tomcat_enabled: false

health_check_apache_enabled: false

health_check_mnt_point_enabled: false

