health_check_url_enabled: true
health_check_url:
  uploadservice:
    - http
    - 80
    - /connect/uploadservice/services/heartbeat/test

health_check_tomcat_enabled: true
health_tomcat_port: 8080

health_check_apache_enabled: true
health_apache_port: 80

health_check_mnt_point_enabled: true
health_mnt_point:
  - /mnt/dc2share/transition
  - /mnt/checkdocs
  - /mnt/images
