- name: upload script
  copy:
    src: "{{ role_path }}/files/chkauditbeat.sh"
    dest: "/tmp/chkauditbeat.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/chkauditbeat.sh
  args:
    chdir: "/tmp"
  register: chkauditbeat

- debug:
    var: chkauditbeat
