- name: upload script
  copy:
    src: "{{ role_path }}/files/chkfilebeat.sh"
    dest: "/tmp/chkfilebeat.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/chkfilebeat.sh
  args:
    chdir: "/tmp"
  register: chkfilebeat

- debug:
    var: chkfilebeat
