- name: upload script
  copy:
    src: "{{ role_path }}/files/chksplunk.sh"
    dest: "/tmp/chksplunk.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/chksplunk.sh
  args:
    chdir: "/tmp"
  register: chksplunk

- debug:
    var: chksplunk
