- name: upload script
  copy:
    src: "{{ role_path }}/files/chksplunk_IP.sh"
    dest: "/tmp/chksplunk_IP_PROD.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/chksplunk_IP.sh 172.18.100.217 dev
  args:
    chdir: "/tmp"
  register: chksplunk

- debug:
    var: chksplunk
