- name: Create directory /tmp/LINUX
  file:
    path: /tmp/LINUX
    state: directory

- name: upload LINUX
  copy:
    src: "{{ role_path }}/files/LINUX"
    dest: "/tmp"

#- name: Changing perm of "/tmp/LINUX/ctagent_e_setup_linux_x64_04002000_17139_20200728.run"
#  file: dest=/tmp/LINUX/ctagent_e_setup_linux_x64_04002000_17139_20200728.run mode=777

#- name: Changing perm of "ctagent_e_setup_linux_x86_04002000_17139_20200728.run"
#  file: dest=/tmp/LINUX/ctagent_e_setup_linux_x86_04002000_17139_20200728.run mode=777

