- name: upload script
  copy:
    src: "{{ role_path }}/files/cs.sh"
    dest: "/tmp/cs.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/cs.sh
  args:
    chdir: "/tmp"
  register: cs

- debug:
    var: cs
