- name: upload script
  copy:
    src: "{{ role_path }}/files/cs6.sh"
    dest: "/tmp/cs6.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/cs6.sh
  args:
    chdir: "/tmp"
  register: cs6

- debug:
    var: cs6
