- name: upload docker_install1 script
  copy:
    src: "{{ role_path }}/files/docker_install1.sh"
    dest: "/tmp/docker_install1.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/docker_install1.sh
  args:
    chdir: "/tmp"
  register: dockerinstall1

- debug:
    var: dockerinstall1
