- name: upload script
  copy:
    src: "{{ role_path }}/files/fixPRODsplunk.sh"
    dest: "/tmp/fixPRODsplunk.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/fixPRODsplunk.sh
  args:
    chdir: "/tmp"
  register: fixPRODsplunk

- debug:
    var: fixPRODsplunk
