- name: Create directory /tmp/LINUX
  file:
    path: /tmp/LINUX
    state: directory

- name: upload LINUX
  copy:
    src: "{{ role_path }}/files/LINUX"
    dest: "/tmp"

- name: upload installIt.sh
  copy:
    src: "{{ role_path }}/files/installCim.sh"
    dest: "/tmp/LINUX/installCim.sh"
    mode: "0755"
    force: yes

- name: Changing perm of "/tmp/LINUX/ctagent_e_setup_linux_x64_04002000_17139_20200728.run"
  file: dest=/tmp/LINUX/ctagent_e_setup_linux_x64_04002000_17139_20200728.run mode=777

- name: Changing perm of "ctagent_e_setup_linux_x86_04002000_17139_20200728.run"
  file: dest=/tmp/LINUX/ctagent_e_setup_linux_x86_04002000_17139_20200728.run mode=777

- name: execute
  shell: sh /tmp/LINUX/installCim.sh
  args:
    chdir: "/tmp/LINUX"
  register: installCim

- debug:
    var: installCim
