- name: upload script
  copy:
    src: "{{ role_path }}/files/java_chk.sh"
    dest: "/tmp/java_chk.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/java_chk.sh
  args:
    chdir: "/tmp"
  register: java_chk

- debug:
    var: java_chk
