- name: upload script
  copy:
    src: "{{ role_path }}/files/mnt_check.sh"
    dest: "/tmp/mnt_check.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/mnt_check.sh
  args:
    chdir: "/tmp"
  register: mnt_check

- debug:
    var: mnt_check
