- name: upload script
  copy:
    src: "{{ role_path }}/files/mnt_check_ALL.sh"
    dest: "/tmp/mnt_check_ALL.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/mnt_check_ALL.sh
  args:
    chdir: "/tmp"
  register: mnt_check_ALL

- debug:
    var: mnt_check_ALL
