- name: upload script
  copy:
    src: "{{ role_path }}/files/realmstep2.sh"
    dest: "/tmp/realmstep2.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/realmstep2.sh
  args:
    chdir: "/tmp"
  register: realmstep2

- debug:
    var: realmstep2
