- name: upload script
  copy:
    src: "{{ role_path }}/files/realmstep1.sh"
    dest: "/tmp/realmstep1.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/realmstep1.sh
  args:
    chdir: "/tmp"
  register: realmstep1

- debug:
    var: realmstep1
