- name: upload script
  copy:
    src: "{{ role_path }}/files/removefilebeat.sh"
    dest: "/tmp/removefilebeat.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/removefilebeat.sh
  args:
    chdir: "/tmp"
  register: removefilebeat

- debug:
    var: removefilebeat
