- name: upload script
  copy:
    src: "{{ role_path }}/files/removeTanium.sh"
    dest: "/tmp/removeTanium.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/removeTanium.sh
  args:
    chdir: "/tmp"
  register: removeTainium

- debug:
    var: removeTanium
