- name: upload script
  copy:
    src: "{{ role_path }}/files/removeauditbeat.sh"
    dest: "/tmp/removeauditbeat.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/removeauditbeat.sh
  args:
    chdir: "/tmp"
  register: removeauditbeat

- debug:
    var: removeauditbeat
