- name: upload script
  copy:
    src: "{{ role_path }}/files/restartsplunk.sh"
    dest: "/tmp/restartsplunk.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/restartsplunk.sh
  args:
    chdir: "/tmp"
  register: restartsplunk

- debug:
    var: restartsplunk
