- name: upload script
  copy:
    src: "{{ role_path }}/files/splunk_dev.sh"
    dest: "/tmp/splunk_dev.sh"
    mode: "777"
    force: yes

- name: execute
  shell: sh /tmp/splunk_dev.sh
  args:
    chdir: "/tmp"
  register: splunk_dev

- debug:
    var: splunk_dev
