- name: Create directory /tmp/LINUX
  file:
    path: /tmp/LINUX
    state: directory

- name: upload service_chk_and_restart.yml
  copy:
    src: "{{ role_path }}/files/service_chk_and_restart.sh"
    dest: "/tmp/LINUX/service_chk_and_restart.sh"
    mode: "0755"
    force: yes

- name: execute
  shell: sh /tmp/LINUX/service_chk_and_restart.sh
  args:
    chdir: "/tmp/LINUX"
  register: service_chk_and_restart

- debug:
    var: service_chk_and_restart
