- service:
    name: elasticsearch
    state: stopped

- when: upgradeKibana | default(false) 
  service:
    name: kibana
    state: stopped

- copy:
    src: "{{playbook_dir}}/files/elastic.repo"
    dest: /etc/yum.repos.d/elastic.repo
    force: yes

- shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
  ignore_errors: yes
  
- name: update repo
  shell: yum check-update --disablerepo=* --enablerepo=elastic
  ignore_errors: yes

- yum:
    name: elasticsearch-6.8.10
    state: present
    disablerepo: "*"
    enablerepo: elastic

- when: upgradeKibana | default(false) 
  yum:
    name: kibana-6.8.10
    state: present
    disablerepo: "*"
    enablerepo: elastic

# yum update will not overwrite existing files, these command will fix it
- shell: mv elasticsearch.service elasticsearch.service.linuxPatch.bak; mv elasticsearch.service.rpmnew elasticsearch.service
  args:
    chdir: /usr/lib/systemd/system
    removes: elasticsearch.service.rpmnew

- shell: mv elasticsearch elasticsearch.linuxPatch.bak; mv elasticsearch.rpmnew elasticsearch
  args:
    chdir: /etc/sysconfig
    removes: elasticsearch.rpmnew

- shell: systemctl daemon-reload; chmod 770 /etc/elasticsearch
  ignore_errors: yes

- name: fix elasticsearch.yml
  include_tasks: propertiesFixUp.yml
  vars:
    service: 
      configPath: /etc/elasticsearch/elasticsearch.yml
      propertyUpdates: 
        - "path.data: /var/lib/elasticsearch"
        - "path.logs: /var/log/elasticsearch"

- service:
    name: elasticsearch
    state: started

- wait_for:
    port: 9200
    state: started