# Last modified: Mon Jun 15 16:40:38 EDT 2020

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: true
  become: yes
#  pre_tasks:
#    - name: Include all main.yaml file for the ENV
#      include_vars: "vars/{{envVar}}/main.yml"
#    - name: Include file for the Env/Application
#      include_vars: "vars/{{envVar}}/{{applicationVar}}.yml"

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: true
  become: yes
  pre_tasks:
    - name: Include all main.yaml file for the ENV
      include_vars: "vars/{{envVar}}/main.yml"
    - name: Include file for the Env/Application
      include_vars: "vars/{{envVar}}/{{applicationVar}}.yml"
  tasks:
    - import_role:
        name: patchCheck
        tasks_from: chk_service_Fireeye.yml

    - name:
      shell: rm -f /tmp/small_chk_services.sh ; rm -rf tmp_status*
      args:
        warn: no

    - name:
      shell: rm -f /usr/local/small_chk_services.sh ; rm -rf tmp_status*
      args:
        warn: no

