# This playbook will: perform a patch and run an applicaiton check
# Last modified: 9/9/21

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: true
  become: yes
#  pre_tasks:
#    - name: Include all main.yaml file for the ENV
#      include_vars: "vars/{{envVar}}/main.yml"
#    - name: Include file for the Env/Application
#      include_vars: "vars/{{envVar}}/{{applicationVar}}.yml"
#    - import_role:
#       name: patchCheck
#       tasks_from: removeauditbeat
  pre_tasks:
    - name: Include all main.yaml file for the ENV
      include_vars: "vars/{{envVar}}/main.yml"
    - name: Include file for the Env/Application
      include_vars: "vars/{{envVar}}/{{applicationVar}}.yml"
  tasks:

    - import_role:
        name: patchCheck
        tasks_from: chkfilebeat.yml

#    - name:
#      shell: rm -f /tmp/chkfilebeat.sh
#      args:
#        warn: no

#    - name:
#      shell: rm -f /usr/local/chkfilebeat.sh
#      args:
#        warn: no

