# This playbook will: perform a patch and run an applicaiton check
# Last modified: 9/9/21

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: true
  become: yes
#  pre_tasks:
#    - name: Include all main.yaml file for the ENV
#      include_vars: "vars/{{envVar}}/main.yml"
#    - name: Include file for the Env/Application
#      include_vars: "vars/{{envVar}}/{{applicationVar}}.yml"
  tasks:

#    - copy:
#        src: "files/NessusAgent-10.1.3-es7.x86_64.rpm"
#        dest: /tmp

#    - copy:
#        src: "files/Nessus-8.15.8-es6.x86_64.rpm"
#        dest: /tmp

    - import_role:
       name: patchCheck
       tasks_from: chknessus

    - name:
      shell: rm -f /tmp/chknessus.sh
      args:
        warn: no

    - name:
      shell: rm -f /tmp/NessusAgent-10.1.3-es7.x86_64.rpm
      args:
        warn: no

    - name:
      shell: rm -f /tmp/Nessus-8.15.8-es6.x86_64.rpm
      args:
        warn: no


    - name: remove junk
      shell: rm -f /tmp/tmp_status* ; rm -f nessus.sh 
      args:
        warn: no
