# This playbook will: import root cert and make a backup
# Last modified:  Thu Jun 10 13:11:22 EST 2021

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: true
  become: yes
  pre_tasks:
    - name: Include all main.yaml file for the ENV
      include_vars: "vars/{{envVar}}/main.yml"
    - name: Include file for the Env/Application
      include_vars: "vars/{{envVar}}/{{applicationVar}}.yml"
  tasks:
#    - copy:
#        src: "{{playbook_dir}}/files/yum.conf"
#        dest: /etc/yum.conf

#    - name: install yum util 
#      shell: yum install yum-utils
#      args:
#        warn: no

    - name: remove junk
      shell: rm -f /tmp/tmp_status* ; rm -f nessus.sh ; rm -rf /tmp/snow
      args:
        warn: no

    - name: remove junk1
      shell: rm -t /tmp/splunkforwarder-9.0.1-82c987350fde-Linux-x86_64.tgz ; rm -f /tmp/removeTanium.sh ; rm -f /tmp/removeTanium.sh  
      args:
        warn: no

    - name: remove junk2
      shell: rm -f /tmp/removeTanium.sh ; rm -f chkME.sh ; rm -f chkSnow.sh ; rm -f /tmp/cs.sh ; rm -f /tmp/NessusAgent-10.1.3-es7.x86_64.rpm ; rm -f nessus.sh ; rm -rf /tmp/chkcs.sh ; rm -f /tmp/chksplunk.sh ; rm -f /tmp/splunk.sh
      args:
        warn: no

