# This playbook will: perform a patch and run an applicaiton check
# Last modified: 9/9/21

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: true
  become: yes
#  pre_tasks:
#    - name: Include all main.yaml file for the ENV
#      include_vars: "vars/{{envVar}}/main.yml"
#    - name: Include file for the Env/Application
#      include_vars: "vars/{{envVar}}/{{applicationVar}}.yml"
  tasks:

    - copy:
        src: "files/falcon-sensor-6.50.0-14712.el6.x86_64.rpm"
        dest: /tmp

    - import_role:
       name: patchCheck
       tasks_from: cs

    - name:
      shell: rm -f /tmp/cs6.sh
      args:
        warn: no

    - name:
      shell: rm -f /tmp/falcon-sensor-6.50.0-14712.el6.x86_64.rpm
      args:
        warn: no
    - name:
      shell: rm -f /tmp/falcon-sensor-6.46.0-14306.el7.x86_64.rpm
      args:
        warn: no

