# This playbook will: perform a patch and run an applicaiton check
# Last modified: Thu Jul  6 12:55:01 EST 2023

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: false
#  gather_facts: true
  become: yes
  tasks:

    - name: wget
      shell: wget https://www.openssl.org/source/openssl-1.1.1v.tar.gz
      args:
        warn: no

    - name: openssl-1.1.1v.tar.gz
      shell: tar -xf openssl-1.1.1v.tar.gz
      args:
        warn: no

    - name: cd openssl-1.1.1v
      shell: cd openssl-1.1.1v
      args:
        warn: no

    - name: ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl
      shell: ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl
      args:
        warn: no

    - name: yum install gcc -y
      shell: yum install gcc -y
      args:
        warn: no

    - name: make
      shell: make
      args:
        warn: no

    - name: make install
      shell: make install
      args:
        warn: no

    - name: echo "/usr/local/openssl/lib" > /etc/ld.so.conf.d/openssl.conf
      shell: echo "/usr/local/openssl/lib" > /etc/ld.so.conf.d/openssl.conf
      args:
        warn: no

    - name: ldconfig
      shell: ldconfig
      args:
        warn: no

#    - name: /usr/local/openssl/bin/openssl version
#      shell: /usr/local/openssl/bin/openssl version
#      args:
#        warn: no
