- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: false
  tasks:
    - import_role:
        name: f5
        tasks_from: getF5Info
      tags: 
        - f5
    - import_role:
        name: healthCheck
      tags: 
        - healthCheck
    - import_role:
        name: f5
        tasks_from: enableAllF5
      tags: 
        - f5

# - hosts: all
#   gather_facts: false
#   serial: '50%'
#   tasks:
#     - pause:
#         seconds: 10
#     - import_role:
#         name: f5
#         tasks_from: disableAllF5
#     - pause:
#         seconds: 20
#     - import_role:
#         name: f5
#         tasks_from: enableAllF5