# This playbook will: perform a patch and run an applicaiton check
# Last modified: 9/9/21

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: true
  become: yes
#  pre_tasks:
#    - name: Include all main.yaml file for the ENV
#      include_vars: "vars/{{envVar}}/main.yml"
#    - name: Include file for the Env/Application
#      include_vars: "vars/{{envVar}}/{{applicationVar}}.yml"
  tasks:
    - copy:
        src: "files/IMAGE_HX_AGENT_LINUX_32.30.12.tgz"
        dest: /tmp
#    - copy:
#        src: "/opt/fireeye"
#        dest: /opt
    - import_role:
       name: patchCheck
       tasks_from: FireEye
