# This playbook will: perform a patch and run an applicaiton check
# Last modified: Fri Jul 17 15:39:09 EST 2020

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: true
  become: yes
#  pre_tasks:
#    - name: Include all main.yaml file for the ENV
#      include_vars: "vars/{{envVar}}/main.yml"
#    - name: Include file for the Env/Application
#      include_vars: "vars/{{envVar}}/{{applicationVar}}.yml"
  tasks:
    - copy:
        src: "files/IMAGE_HX_AGENT_LINUX_32.30.12.tgz"
        dest: /tmp
    - import_role:
       name: patchCheck
       tasks_from: FireEye
