# This playbook will: perform a patch and run an applicaiton check
# Last modified: Wed Nov  2 16:51:51 EST 2022

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: false
  become: yes
#  pre_tasks:
#    - name: Include all main.yaml file for the ENV
#      include_vars: "vars/{{envVar}}/main.yml"
#    - name: Include file for the Env/Application
#      include_vars: "vars/{{envVar}}/{{applicationVar}}.yml"
  tasks:
    - import_role:
       name: patchCheck
       tasks_from: fixsplunk.yml

    - name:
      shell: touch /opt/splunkforwarder/etc/system/local/deploymentclient.conf
      args:
        warn: no
    - name:
      shell: rm -f /tmp/splunkforwarder-9.0.1-82c987350fde-Linux-x86_64.tgz ; rm -f /tmp/splunk* ; rm -f /tmp/fixsplun*
      args:
        warn: no

    - name:
      shell: rm -f /tmp/splunkforwarder-9.0.1-82c987350fde-Linux-x86_64.tgz
      args:
        warn: no

    - name: remove junk
      shell: rm -f /tmp/tmp_status* 
      args:
        warn: no

    - name: remove junk1
      shell: rm -t /tmp/splunkforwarder-9.0.1-82c987350fde-Linux-x86_64.tgz 
      args:
        warn: no

