# This playbook will: perform a patch and run an applicaiton check
# Last modified: 5/3 150PM 

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: true
  become: yes
  ### any_errors_fatal: True
  tasks:

#    - import_role:
#       name: patchCheck
#       tasks_from: restarttomcat_dev4.yml

    - import_role:
       name: patchCheck
       tasks_from: chk_tomcat.yml

#    - name: sleep a few mins
#      shell: sleep 360
#      args:
#        warn: no

#    - import_role:
#       name: patchCheck
#       tasks_from: restarttomcat2.yml

#    - import_role:
#       name: patchCheck
#       tasks_from: chk_tomcat.yml
#
#    - name: sleep a few mins
#      shell: sleep 360
#      args:
#        warn: no

#    - import_role:
#       name: patchCheck
#       tasks_from: restarttomcat3.yml
#
#    - import_role:
#       name: patchCheck
#       tasks_from: chk_tomcat.yml

#    - name: sleep a few mins
#      shell: sleep 300
#      args:
#        warn: no

#    - import_role:
#       name: patchCheck
#       tasks_from: restarttomcat4.yml
#
#    - import_role:
#       name: patchCheck
#       tasks_from: chk_tomcat.yml


#    - name: remove junk
#      shell: rm -f /tmp/tmp_status* 
#      args:
#        warn: no

#    - name: remove junk1
#      shell: rm -t /tmp/restarttomca*
#      args:
#        warn: no
