# This playbook will: install cimtrack 
# Last modified:  Mon Jan 25 08:48:42 CST 2021

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: true
  become: yes
  tasks:
    - import_role:
        name: patchCheck
        tasks_from: cim_before
