# This playbook will: perform a patch and run an applicaiton check
# Last modified: Mon Jun 22 10:13:05 EST 2020

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: true
  become: yes
  pre_tasks:
    - name: Include all main.yaml file for the ENV
      include_vars: "vars/{{envVar}}/main.yml"
    - name: Include file for the Env/Application
      include_vars: "vars/{{envVar}}/{{applicationVar}}.yml"
  tasks:
    - import_role:
        name: f5
        tasks_from: getF5Info
      when: envVar in ['Env_SG','Env_PR']
    - import_role:
        name: healthCheck

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: true
  serial: 1
  become: yes
  pre_tasks:
    - name: Include all main.yaml file for the ENV
      include_vars: "vars/{{envVar}}/main.yml"
    - name: Include file for the Env/Application
      include_vars: "vars/{{envVar}}/{{applicationVar}}.yml"
  tasks:
    - import_role:
        name: f5
        tasks_from: disableAllF5
      when: envVar in ['Env_SG','Env_PR']
    - import_role:
       name: vcenter
       tasks_from: poweroffVM.yml
    - import_role:
       name: vcenter
       tasks_from: poweronVM.yml
    - name: Wait 60 seconds, but only start checking after 120 seconds
      wait_for_connection:
        delay: 60
        timeout: 120
    - include_role:
        name: tomcat8
        tasks_from: waitUntilTomcatStart
    - import_role:
        name: healthCheck
    - when: healthCheckHasError
      import_role:
        name: slack
      vars:
        slack_color: danger
        slack_msg: "Health check failed {{envVar | default('')}} {{applicationVar | default('')}}, please fix the errors. Remember to enable f5 if needed."
      delegate_to: localhost
      run_once: true
    - when: healthCheckHasError
      fail:
        msg: "Health check failed."
    - import_role:
        name: f5
        tasks_from: enableAllF5
      when: envVar in ['Env_SG','Env_PR'] and not healthCheckHasError