# This playbook will: import root cert and make a backup
# Last modified:  Thu Jun 10 13:11:22 EST 2021

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: true
  become: yes
  pre_tasks:
    - name: Include all main.yaml file for the ENV
      include_vars: "vars/{{envVar}}/main.yml"
    - name: Include file for the Env/Application
      include_vars: "vars/{{envVar}}/{{applicationVar}}.yml"
  tasks:

    - name: install nss
      shell: yum -y install nss-devel
      args:
        warn: no

    - name: update nss
      shell: yum -y update nss-devel
      args:
        warn: no

#    - name: remove1 kern.log
#      shell: echo " " > /var/log/kern.log
#      args:
#        warn: no
#
#    - name: remove2 /var/cache/yum/
#      shell: rm -rf /var/cache/yum/
#      args:
#        warn: no
#
#    - name: remove3 messages-
#      shell: echo " " > /var/log/messages
#      args:
#        warn: no
#
#    - name: remove4 messages-
#      shell: rm -rf /var/log/messages-*
#      args:
#        warn: no
#
#    - name: remove5 /var/log/lastlog
#      shell: echo " " > /var/log/lastlog
#      args:
#        warn: no
