---
- hosts: all
  become: true
  tasks:
    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Create GPG key directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Download and de-armor Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg
        tmp_dest: /tmp/docker_gpg_tmp
        mode: 0644
        checksum: "SHA256:a09e26b72228e330d55bf134b8eaca57365ef44bf70b8e27c5f55ea87a8b05e2"

    - name: Add Docker repository entry
      copy:
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu   jammy stable
        dest: /etc/apt/sources.list.d/docker.list

    - name: Update package list
      apt:
        update_cache: yes
        state: present

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Verify Docker installation
      command: docker --version

    - name: Print confirmation message
      debug:
        msg: "Docker installation completed!"

