# This playbook will: perform a patch and run an applicaiton check
# Last modified:  6/10/21

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: true
  become: yes
  pre_tasks:
    - name: Include all main.yaml file for the ENV
      include_vars: "vars/{{envVar}}/main.yml"
    - name: Include file for the Env/Application
      include_vars: "vars/{{envVar}}/{{applicationVar}}.yml"
  tasks:

    - shell: cat /etc/redhat-release
      register: osVersion

    - import_role:
        name: vcenter
        tasks_from: createAttribute
      vars:
        vcenterAttributeArray:
          - name: lastUpdatedTime
            value: "{{ lookup('pipe','date') }}"
          - name: osVersion
            value: "{{ osVersion.stdout }}"
