# This playbook will: perform a patch and run an applicaiton check
# Last modified: Thu Jul  6 12:55:01 EST 2023

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: false
#  gather_facts: true
  become: yes
  tasks:

#    - name:  mkdir /root or /usr or /opt  ???  
# do this seperate then run the cs install play 
#    - name: yum remove openssl
#      shell: yum remove openssl
#      args:
#        warn: no
# 
    - name: yum install libtool perl-core zlib-devel -y
      shell: yum install libtool perl-core zlib-devel -y
      args:
        warn: no
 
    - name: cd /usr/local/src
      shell: cd /usr/local/src ; wget https://www.openssl.org/source/openssl-3.2.0.tar.gz ; sleep 1 ; tar -xf openssl-3.2.0.tar.gz ; cd openssl-3.2.0
      args:
        warn: no
 
#  cd /usr/local/src/openssl-3.2.0

#    - name: wget
#      shell: wget https://www.openssl.org/source/openssl-3.2.0.tar.gz
#      args:
#        warn: no
#    - name: tar 
#      shell: tar -xf openssl-3.2.0.tar.gz
#      args:
#        warn: no
#    - name: cd openssl-3.2.0
#      shell: cd openssl-3.2.0
#      args:
#        warn: no
#    - name:  yum install perl-IPC-Cmd -y
#      shell: yum install perl-IPC-Cmd -y
#      args:
#        warn: no

#      shell: echo "/usr/local/openssl/lib" > /etc/ld.so.conf.d/openssl.conf
#      shell: echo "/usr/local/openssl/lib" > /etc/ld.so.conf.d/openssl.conf
# cat /etc/profile.d/openssl.sh
#pathmunge /usr/local/openssl/bin
# chmod 777 /etc/profile.d/openssl.sh
#[root@dvbosljeffa01 openssl-3.2.0]# mkdir /etc/ld.so
#[root@dvbosljeffa01 openssl-3.2.0]# mkdir /etc/ld.so/conf.d
#[root@dvbosljeffa01 openssl-3.2.0]# vi /etc/ld.so/conf.d/openssl3.2.0.conf
#/usr/local/openssl/lib
############# the below did not work
#    - name: ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl shared zlib
#      shell: ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl shared zlib
#      args:
#        warn: no
############# the below did not work
#    - name: make
#      shell: make
#      args:
#        warn: no
#    - name: make
#ln -s /usr/local/ssl/bin/openssl /usr/bin/openssl
#  make test 
#  make install
#  ldconfig -v
#   ldconfig /usr/local/lib64/
#   /usr/local/openssl/bin/openssl version
# openssl version
#  ps -ef | grep falcon 
