# This playbook will: perform a patch and run an applicaiton check
# Last modified: Thu Jul  6 12:55:01 EST 2023

- hosts: "{{envVar}}:&{{applicationVar}}"
  gather_facts: false
#  gather_facts: true
  become: yes
  tasks:

#    - name:  mkdir /opt/openssl
#      shell: mkdir /opt/openssl 
#      args:
#        warn: no
#    - name:  mkdir /opt/openssl/bin
#      shell: mkdir /opt/openssl/bin 
#      args:
#        warn: no
    - name: cd /opt/openssl
      shell: cd /opt/openssl 
      args:
        warn: no
 
    - name: wget
      shell: wget https://www.openssl.org/source/openssl-3.2.0.tar.gz
      args:
        warn: no

    - name: tar 
      shell: tar -xf openssl-3.2.0.tar.gz
      args:
        warn: no

    - name: cd openssl-3.2.0
      shell: cd openssl-3.2.0
      args:
        warn: no

    - name:  yum install perl-IPC-Cmd -y
      shell: yum install perl-IPC-Cmd -y
      args:
        warn: no

