health_check_url_enabled: false

health_check_tomcat_enabled: true
health_tomcat_port: 8080

health_check_apache_enabled: false
health_apache_port: 80

health_check_mnt_point_enabled: true
health_mnt_point:
  - /mnt/auto/nas02/netops/env-tools/devnet
  - /mnt/edisdocs