health_check_url_enabled: true
health_check_url:
  # Team: Dischared 2.0 | mnt: cred.xml, edisdocs, aws_edisdocs, ediscache (DEV/QA), pdfcache
  printservcie:
    - https
    - 443
    - connect/printservice/health

health_check_tomcat_enabled: true
health_tomcat_port: 8080

health_check_apache_enabled: true
health_apache_port: 80

health_check_mnt_point_enabled: true
health_mnt_point:
  - /mnt/auto/nas02/netops/env-tools/devnet
  - /mnt/ediscache/cache
  - /mnt/edisdocs
  - /mnt/aws_edisdocs
  - /mnt/pdfcache
  - /mnt/images