# - name: remove existing snapshot
#   become: no
#   vmware_guest_snapshot:
#     hostname: "{{ bosVcenter.host }}"
#     username: "{{ bosVcenter.username }}"
#     password: "{{ bosVcenter.password }}"
#     datacenter: "{{ bosVcenter.datacenter }}"
#     folder: "{{ vcenterFolder }}"
#     name: "{{ inventory_hostname_short }}"
#     state: absent
#     snapshot_name: "linuxPatching"
#     description: linuxPatching
#     validate_certs : false
#   delegate_to: localhost

- set_fact:
# prod va vcenter      targetVcenter: "{{ targetVcenter | default(iadVcenter) }}"
#    targetVcenter: "{{ targetVcenter | default(iadVcenter) }}"
#  below is p10 "mostly windows but some unix" vcenter  
#    targetVcenter: "{{ targetVcenter | default(bnaVcenter) }}"
#  below is  dev
    targetVcenter: "{{ targetVcenter | default(bosVcenter) }}"
  
- name: create snapshot
  become: no
  vmware_guest_snapshot:
    hostname: "{{ targetVcenter.host }}"
    username: "{{ targetVcenter.username }}"
    password: "{{ targetVcenter.password }}"
    datacenter: "{{ targetVcenter.datacenter }}"
    folder: "{{ vcenterFolder }}"
    name: "{{ nodeNameInVcenter | default(inventory_hostname_short) }}"
    state: present
    snapshot_name: "linuxPatching"
    description: linuxPatching
    validate_certs : false
    quiesce: true
    memory_dump: true
  delegate_to: localhost
