- set_fact:
    targetVcenter: "{{ targetVcenter | default(bosVcenter) }}"

- name: Set the state of a virtual machine to poweron
  become: no
  vmware_guest_powerstate:
    hostname: "{{ targetVcenter.host }}"
    username: "{{ targetVcenter.username }}"
    password: "{{ targetVcenter.password }}"
    folder: "{{ vcenterFolder }}"
    name: "{{ nodeNameInVcenter | default(inventory_hostname_short) }}"
    state: powered-on
    validate_certs: no
  delegate_to: localhost